language: android

android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository

branches:
  only:
  - main

install:
  - chmod +x ./gradlew

script: ./gradlew clean assembleDebug