language: android
dist: trusty

android:
  components:
  - platform-tools
  - tools
  - build-tools-29.0.2
  - android-29
  - extra-google-m2repository
  - extra-android-m2repository

branches:
  only:
  - main

install:
  - chmod +x ./gradlew